/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        primary: {
          50: "#fdf2f8",
          100: "#fce7f3",
          200: "#fbcfe8",
          300: "#f9a8d4",
          400: "#f472b6",
          500: "#F7AAD6",
          600: "#db2777",
          700: "#be185d",
          800: "#9d174d",
          900: "#831843",
          background: "var(--color-primary-background)",
          button: "var(--color-primary-button)",
          surface: "var(--color-primary-surface)",
          text: "var(--color-primary-text)",
        },
        secondary: {
          50: "#fefcff",
          100: "#fef7ff",
          200: "#feeeff",
          300: "#fdd8ff",
          400: "#FFC0E6",
          500: "#e879f9",
          600: "#d946ef",
          700: "#c026d3",
          800: "#a21caf",
          900: "#86198f",
          tag: "var(--color-secondary-tag)",
          tagLight: "var(--color-secondary-tag-light)",
          tagLighter: "var(--color-secondary-tag-lighter)",
        },
        accent: "#FFD6EF",
        background: {
          primary: "var(--color-primary-background)",
          secondary: "var(--color-primary-button)",
          card: "var(--color-other-border)",
        },
        border: {
          light: "var(--color-primary-surface)",
          medium: "var(--color-primary-text)",
          divider: "var(--color-other-lining)",
          disabled: "var(--color-other-disabled)",
        },
        theme: {
          primaryBg: "var(--color-primary-background)",
          primaryBtn: "var(--color-primary-button)",
          primarySurface: "var(--color-primary-surface)",
          primaryText: "var(--color-primary-text)",
          secondaryTag: "var(--color-secondary-tag)",
          secondaryTagLight: "var(--color-secondary-tag-light)",
          secondaryTagLighter: "var(--color-secondary-tag-lighter)",
          authorBg: "var(--color-author-background)",
          authorText: "var(--color-author-text)",
          authorBorder: "var(--color-author-border)",
          authorHoverBg: "var(--color-author-hover-background)",
          authorHoverBorder: "var(--color-author-hover-border)",
          cardBg: "var(--color-card-background)",
          cardBorder: "var(--color-card-border)",
          moodBg: "var(--color-mood-background)",
          moodText: "var(--color-mood-text)",
          moodHoverBg: "var(--color-mood-hover-background)",
          tabActiveBg: "var(--color-tab-active-background)",
          tabActiveText: "var(--color-tab-active-text)",
          tabInactiveBg: "var(--color-tab-inactive-background)",
          tabInactiveText: "var(--color-tab-inactive-text)",
          otherBorder: "var(--color-other-border)",
          otherLining: "var(--color-other-lining)",
          otherDisabled: "var(--color-other-disabled)",
        },
      },
      fontFamily: {
        sans: ["Inter", "system-ui", "sans-serif"],
      },
    },
  },
  plugins: [],
};
