name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Type check
        run: npx tsc --noEmit

      - name: Build project
        run: npm run build

      - name: Create Firebase credentials file
        run: echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT_QUOTE_SWIPE }}' > $HOME/gcp-key.json

      - name: Deploy to Firebase Hosting
        run: |
          npm install -g firebase-tools
          export GOOGLE_APPLICATION_CREDENTIALS=$HOME/gcp-key.json
          firebase deploy --only hosting --project quote-swipe --non-interactive

      - name: Clean up credentials
        if: always()
        run: rm -f $HOME/gcp-key.json
